### ISSUE TITLE
Console input hotkey?

### ISSUE THREAD

**Issue by batcrave** [OpenBuilds/OpenBuilds-CONTROL#112]
Any chance of getting a hotkey (bindable, ideally) to move the cursor straight to the console input line? 

I've been finding myself spending a lot of time working MDI-style lately, and having a way to jump straight back from [wherever] to input another command would be awfully handy.

(and I won't object to an F6 default either, Peter)

**Comment by petervanderwalt** [comment]
F6 assigned (no editable) 
v1.0.220 or up
