### ISSUE TITLE
Wrong tooltip on Reset View button

### ISSUE THREAD

**Issue by batcrave** [OpenBuilds/OpenBuilds-CONTROL#114]
Reset View's mouseover tooltip reads "Stop Sim". Clicking (not surprisingly) does not stop sim.

Labels: MissionCritical; Showstopper; ZOMGBigBug

_(Not because it matters - I just thought I should submit _something_ that wasn't a huge headache to deal with. Now you can mark an issue Resolved & go home early. You're welcome.)_

**Comment by petervanderwalt** [comment]
Fixed in v1.0.211

PS: (: never change. your humour has made me smile so many times.   You got your MissionCritical (;
