### ISSUE TITLE
Go to Zero (work and machine) hot key

### ISSUE THREAD

**Issue by MikonosII** [OpenBuilds/OpenBuilds-CONTROL#115]
As the title says, hot keys for goto zeros would be awesome!

**Comment by petervanderwalt** [comment]
Added gotoworkzero:

![gotozero](https://user-images.githubusercontent.com/31449271/79228459-c4637000-7e61-11ea-87ab-ad968ee4b15a.PNG)

I don't see much use for goto machine zero, at least not enough to warrant a permanent key association at this time (: 

Will be in v 1.0.222 or later (week or two, internal testing etc first)
