### ISSUE TITLE
CONTROL software loaded GCode file name

### ISSUE THREAD

**Issue by rmarshall71** [OpenBuilds/OpenBuilds-CONTROL#116]
I would like to request that when a GCode file is loaded in CONTROL software that the name of the file be displayed somewhere on the screen. When I do a 2 bit carve, some of the output displays look very similar.

**Comment by rscamp** [comment]
> I would like to request that when a GCode file is loaded in CONTROL software that the name of the file be displayed somewhere on the screen. When I do a 2 bit carve, some of the output displays look very similar.

Thanks for requesting this, Ron.

**Comment by petervanderwalt** [comment]
Implemented in 1.0.220 or later

**Comment by petervanderwalt** [comment]
![titlebar](https://user-images.githubusercontent.com/31449271/77915603-0ef8c000-7298-11ea-8280-37b97c947beb.PNG)

**Comment by rmarshall71** [comment]
Thank you. When will the update be released? I am running 1.0.215 and it doesn't find the update yet. No hurry, just asking.

**Comment by petervanderwalt** [comment]
In a day or two. Internal testing, management approval etc (:

**Comment by rmarshall71** [comment]
Like I said, no hurry. I appreciate you adding this feature. I love the software.

Ron
