### ISSUE TITLE
Problem with Raspberry PI - Waiting for USB 

### ISSUE THREAD

**Issue by damzurek** [OpenBuilds/OpenBuilds-CONTROL#117]
I did everything in accordance with: https://github.com/OpenBuilds/OpenBuilds-CONTROL/wiki/Run-on-a-Raspberry-Pi-(No-Compile-Method)

Unfortunately, after installation using the command: cd ~ / Desktop / OpenBuilds-CONTROL; node index.js
no tasks are performed.

After connecting the BlackBox OpenBuilds control board, entering the RPI IP number (192.168.1.xxx:3000/jog) into the browser, the message Waiting for USB appears.
I will be grateful for your answer what I can do.
Additional question: On the screenshots I see the application window running on RPI desktops.
Unfortunately, after using node index.js this window does not appear.
I can only get to the IP number.

**Comment by petervanderwalt** [comment]
No technical support for RPi as per the wiki. 
But 
- sure user is part of the dialout group?
- run with DEBUGCONTROL=true node index.js for more logging to help you troubleshoot
