### ISSUE TITLE
File Assoc: Opening gcode file in windows launches control, but no longer fills in gcode editor/preview

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#119]

**Comment by batcrave** [comment]
I'd just noticed this same behavior last night on linux - using "Open With..." on a file would launch the UI, but not load the file. I assumed it was probably the fault of xfce, the file manager, or the way I had them configured, but, yeah, it looks like I can confirm it on Win 7 too.

**Comment by petervanderwalt** [comment]
Fixed in 1.0.220 or later
