### ISSUE TITLE
Jogging Hotkeys: Include Continuous Jog Mode

### ISSUE THREAD

**Issue by brrian11** [OpenBuilds/OpenBuilds-CONTROL#121]
Keys (+) & (-) step through the jog distances. it would be nice if it stepped into & out of continuous jog mode as well. I use a wireless USB numeric keypad with my machine & this would keep me from having to go back to the machine to change jog modes.

**Comment by petervanderwalt** [comment]
Implemented in v1.0.222 or later (will be out in a week or so, internal testing etc first)

![done](https://user-images.githubusercontent.com/31449271/79227701-9598ca00-7e60-11ea-8751-05257c3bdd4a.PNG)

Bonus: if you are in continuous mode, and hit +/- it jumps back to Incremental too (just felt natural in the workflow - as you are used to +/- affecting Incremental functionality, once you go for those, its good that it goes to incremental mode then (:
