### ISSUE TITLE
Option to require homing after startup

### ISSUE THREAD

**Issue by brrian11** [OpenBuilds/OpenBuilds-CONTROL#123]
Grbl says "when homing is enabled. Grbl will lock out all G-code commands until you perform a homing cycle. Meaning no axes motions, unless the lock is disabled ($X)".

In CONTROL, after connection, the Unlock Alarm is blinking. I presume that clicking this disables the lock ($X). My next step would be to home; maybe it isn't everybody's, but if I don't (I forget?) things don't necessarily do what they're supposed to. In my macros with a Z move, they move in the wrong direction. For example, instead of moving to a safe Z height of 40mm above work zero, it wants to plow 40mm into my wasteboard.

My request is a software feature - an option to require homing after connecting CONTROL. Currently, macros and several buttons are greyed out until Unlock Alarm is clicked. If this feature were added, only Home would become active; once the machine was homed, everything would become active.

**Comment by petervanderwalt** [comment]
Works as best we can with what Grbl gives us.  Initial "remember to home" message isnt always sent, software needs events to react to in this case there is not a reliable event to react on.
