### ISSUE TITLE
Timestamp with GCODE filename

### ISSUE THREAD

**Issue by brrian11** [OpenBuilds/OpenBuilds-CONTROL#124]
CONTROL now shows the open GCODE filename in the title bar. It would be helpful to have a timestamp with the filename. If I revise and reopen a file, the timestamp would ensure that I'm using the new version.

**Comment by petervanderwalt** [comment]
Rare use case, can be handled by applying a little effort when saving file (save the modified file as file-v2.gcode, or delete the wrong one) 
You can use Windows Explorer to view modified date, we aren't planning on replacing the OS too (:
