### ISSUE TITLE
Famous Wizards of the Surface World (an anthology of  Surfacing wizard notes, issues, requests, and unreasonable demands)

### ISSUE THREAD

**Issue by batcrave** [OpenBuilds/OpenBuilds-CONTROL#130]
A few notes on the surfacing wizard (which I finally played with for the first time yesterday). Apologies for clumping everything together, but a few seemed related, and a few others didn't seem to warrant their own issue.

1. Surfacing wizard has no spin-up delay on start. This becomes more of a problem the closer the spindle's current position is to the wizard's starting position, as I learned when it slammed a not-yet-moving spindle down into the stock from ~5mm away. 

    An app-wide spinup delay setting would be nice (this is your cue to tell me it already exists somewhere in the firmware), but as a simple compromise, any chance of including something like a "G4 P5" after the M3?

2. Related: A setting for spindle speed would be nice - or at least defaulting to something other than M3 S1000 (which seems to ignore grbl's $30/31 min/max speeds). If you don't want to go full-speed for whatever reason (I'm sure there are probably some good ones that I just can't think of right now), maybe split the difference with something like ($30+$31)/2? That should still cover the "It's a damn trim router - just _turn it on_" crowd, while still giving a reasonably useful starting point for spindly sorts.

3. The "Feed" textbox can only show three digits. Not a problem if it were in inches (anyone with a machine that can cut at >999ipm can afford their own programmer to fix the UI), but with mm it makes it really hard to tell what the current feed setting is - whether that's 1000mm/min, 9000mm/min, or if all those zeros had you confused and you'd entered 10001000mm/min.

    Worse still, after you tab out it scrolls to the beginning of the number, making "1001234567" look like a stately 100mm/min.

   Any chance of widening all the input boxes and/or trimming the margin of whitespace to the left of the labels? It looks like the combination of the two is probably responsible for the issue.

   [edit: this actually seems to be - in part - a matter of window size. At default window size, the Windows textbox can show ~4.1 characters, while the linux version shows an even 3 chars. With smaller windows, there's even a fair margin where _no_ digits are visible, before the interface format changes. Shrinking the whitespace to the left of the labels would probably still address at least the default conditions, though. ]

5. Also, glancing at the generated code through a pre-caffeine haze, it looks like it just makes a beeline from the current position to X0 Y0, potentially carving a path through any workholding or workpiece in the way. Any chance of moving to a safe Z (or choosing where a "safe" Z would be) first? It seems to be there's a fairly established way of doing this, but did I mention caffeine?

Wishlist (read: "Moar Opshuns Pleez!") :

- An option to toggle the framing pass on/off (still covering the same area, but just with straight passes)
- An option for single-direction passes (climb or conventional only, which can be helpful for avoiding tearout)
- An angle setting, to optionally run passes along the Y axis (arbitrary degree increments might be fun too, but I can't think of any use case common enough - or _fun_ enough - to justify the headache)

**Comment by petervanderwalt** [comment]
> Surfacing wizard has no spin-up delay on start. This becomes more of a problem the closer the spindle's current position is to the wizard's starting position, as I learned when it slammed a not-yet-moving spindle down into the stock from ~5mm away.

Added 1.8 second spin up. Control has a "No config required" policy

> A setting for spindle speed would be nice 
Sneaked into 1.0.238. Defaults to grbl-default S1000

> The "Feed" textbox can only show three digits 
Upped to 5 digits and limit to 5 digits max too

> Any chance of moving to a safe Z  
Fixed
