### ISSUE TITLE
Custom probe plate thickness setting reverts to 20mm on restart

### ISSUE THREAD

**Issue by batcrave** [OpenBuilds/OpenBuilds-CONTROL#132]
After quitting and restarting the software, the Probe->Advanced->Plate Thickness setting reverts from whatever custom setting had previously been in use to 20mm. 

This can be anywhere from inconvenient to minorly disastrous, depending on how much attention the user is paying.

 I _think_ I've also caught it reverting once or twice without a restart, but I can't confirm that, never mind repro it.

**Comment by petervanderwalt** [comment]
did a quick test over the weekend, and it saves for me.

Couple questions:

- Does X and Y also revert for you?
- Ctrl+Shift+I > Devtools > Console Tab > Enter ```localStorage.getItem('customProbe')``` , press enter, Screenshot

**Comment by petervanderwalt** [comment]
Nevermind, fixed.  Z Probe... Not Custom XYZ   - didnt notice that (;  screenshot next time man (; 

V1.0.238 and up

**Comment by petervanderwalt** [comment]
https://openbuilds.com/threads/openbuilds-control-software-with-z-probe.16385/ says its back

**Comment by petervanderwalt** [comment]
v1.0.251
