### ISSUE TITLE
Request: Release feed rate textbox focus on Enter?

### ISSUE THREAD

**Issue by batcrave** [OpenBuilds/OpenBuilds-CONTROL#134]
Could Enter possibly be made to move the cursor/focus out of the feed rate box, so it's possible to type in a new rate, hit (numpad) enter, and then begin to jog around without having to pick up the mouse and/or reach to the other side of the keyboard for Tab? 

I often end up jogging left-handed while mousing or fiddling with the machine/workpiece with the right, and having to jump from one side of the keyboard to the other throws off any chance of touch typing (I'd say "touch jogging", but that sounds like some sort of kinky running activity).

**Comment by petervanderwalt** [comment]
Fixed v1.0.238 or later
