### ISSUE TITLE
Probe Z-Only Button

### ISSUE THREAD

**Issue by Sindarius** [OpenBuilds/OpenBuilds-CONTROL#138]
I have the OpenBuilds XYZ Probe and it would be great to have a quick click z probe button on the main UI. Normally the only time I probe XY is at the start of a job but I need to Z probe every tool change.  Another alternative that I would be fine with is defaulting to the z only probe and intentionally selecting to do XYZ probing.

**Comment by petervanderwalt** [comment]
![image](https://user-images.githubusercontent.com/31449271/85710322-6ca97680-b6e6-11ea-9173-a5626b4ad087.png)

Already been there for a while (:

**Comment by Sindarius** [comment]
Awesome! I always use the top menu bar buttons so I never saw this. Thank you!
