### ISSUE TITLE
OSX: Continuous jog hangs (get stuck)

### ISSUE THREAD

**Issue by khenderick** [OpenBuilds/OpenBuilds-CONTROL#140]
I've had a few times that when using the continuous jog on osx with the keyboard, it hangs. I release the key, but it keeps moving and eventually runs into the endstops, or worse, crashes my mill in the spoilboard, part or probe.

I don't immediately see what behavior might trigger the issue, except that in such case I'm typically jogging the mill towards the probe, so I'm making lots of small movements on X, Y and Z.

**Comment by petervanderwalt** [comment]
Check if its the same pattern as https://github.com/OpenBuilds/OpenBuilds-CONTROL/issues/73
