### ISSUE TITLE
Independent Z Jog Setting

### ISSUE THREAD

**Issue by Sindarius** [OpenBuilds/OpenBuilds-CONTROL#141]
It would be nice to have an independent z jog setting separate from X/Y. More than once I have accidentally hit page down when jogging and driven my bit into my work piece or wasteboard. 90% of the time when I am moving Z I am only looking to jog it 0.1 or 1mm at a time to carefully move it up and down but want to be able to move X/Y 10mm+ or continuously. It's nice to be able to protect me from myself sometimes.

**Comment by brrian11** [comment]
I second this.

**Comment by petervanderwalt** [comment]
Not at this time, tune your Z acceleration/max rate appropriately and apply focus while operating your machine. Good luck

**Comment by Sindarius** [comment]
![image](https://user-images.githubusercontent.com/12520045/87549944-1475ec80-c674-11ea-8623-41e2dbba3e10.png)

Ended up implementing it myself.

**Comment by petervanderwalt** [comment]
Good, too cluttered for new-users which is the focus of CONTROL.

**Comment by brrian11** [comment]
Not that I think I'll change your mind, but FWIW I don't think that adds clutter at all & it's quite useful and safer, especially for new users.
