### ISSUE TITLE
GUI Not Appearing

### ISSUE THREAD

**Issue by wheemzy1** [OpenBuilds/OpenBuilds-CONTROL#147]
Seems like I am the only one with this issue but for some reason after I installed using .deb file and then trying the appimage, when I launched the app in terminal the terminal appears to launch the app but a graphics window fails to appear. 

Tried on Ubuntu 16.04 and 20.04. 

Any ideas? 

Thanks, 

Matt

**Comment by petervanderwalt** [comment]
We rely on Electron https://www.electronjs.org/ for the GUI, not really inside our control. 
Usually the reason for a blank window is a problem with graphics drivers (as we also use WebGL)
