### ISSUE TITLE
Handle M0s (carbide create) 

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#162]
As per report by @swarfer in https://openbuilds.com/threads/not-responding-when-run-job.16722/#post-105363

**Comment by pelted** [comment]
Would this tie in to issue #26 regarding tool changes?

**Comment by petervanderwalt** [comment]
No (as toolchanges is not live yet)
For now this relates to the fact that Grbl goes into HOLD:0 on M0, but we
don't react to that fact

**Comment by petervanderwalt** [comment]
M0 nou puts the GUI into Pause mode (when grbl enters "Hold:0" state)
