### ISSUE TITLE
Close 'Completed' Dialog on Run by keyboard shortcut (spacebar)

### ISSUE THREAD

**Issue by brrian11** [OpenBuilds/OpenBuilds-CONTROL#171]
The new 'Completed' dialog w/ time is nice, but since many of my jobs repeat, I'm not a fan of having an extra click to get rid of the dialog. I'd prefer the total time to be displayed in another way - maybe in the bottom left corner where the countdown timer is.

A way around the extra click, and something I use anyway, is the spacebar keyboard shortcut to rerun the job. It works and runs the job, but the 'Completed' dialog stays & CONTROL remains grayed out. Would it be possible to automatically close the dialog if a keyboard shortcut is used?

Thank you.

![Completed](https://user-images.githubusercontent.com/63613181/103440875-3f023480-4c17-11eb-8709-0acf8d37aff2.png)

**Comment by sharmstr** [comment]
Does enter clear it?

**Comment by brrian11** [comment]
Just tested & yes, it clears it, whether it's before a keyboard shortcut is used or after.

That doesn't really change the request though - I'd still like it to dismiss itself, at least when a keyboard shortcut is run, but better, upon any user action in CONTROL.

**Comment by petervanderwalt** [comment]
The real issue here, is keyboard shortcuts shouldnt run while the dialog is open... Will fix that instead, rest of behavior is as intended, for a reason

**Comment by brrian11** [comment]
So I'll have to close the dialog before I can run a program, no matter how I do it? If so, may I ask what the reason is?

**Comment by petervanderwalt** [comment]
Enter now closes the dialog, shouldn't be too much effort,thanks! (:
