### ISSUE TITLE
Fall back to different port if occupied

### ISSUE THREAD

**Issue by rstrobl** [OpenBuilds/OpenBuilds-CONTROL#173]
When I started OpenBuilds Control for the first time today, I got this screen. It left me puzzled for a while until I realised that it must be trying to access my Ruby on Rails project that I was running on port 3000. However OpenBuilds Control launched successfully without any hint why I was getting this screen.

<img width="864" alt="Screenshot 2021-01-06 at 11 48 20 PM" src="https://user-images.githubusercontent.com/503385/103827643-bf8ebe00-5079-11eb-8493-3f38994aeb63.png">

The user-friendliest way to solve this would be probably to keep trying other ports for launching the server until it succeeds.

**Comment by petervanderwalt** [comment]
Different ports become a support and local firewall exemption nightmare. In 10k+ regular users, you are the first person with a port conflict, on a project you chose to use ports 3000/3001 (:

That does not justify the effort suggested. Sorry
