### ISSUE TITLE
Find alternate Write location for firmware.bin

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#179]
Windows:
Windows does not provide permission to write to Program Files directory unless you have administrator privileges. Either you have to force user to run you program as administrator or write to a folder like C:\Users\<username>\AppData\Local\<yourappname> as most applications does

Linux:
See #177

**Comment by petervanderwalt** [comment]
Please test v1.0.278 or later

**Comment by sharmstr** [comment]
Firmware is showing up in Control now.  Thank you!
