### ISSUE TITLE
Please consider allowing set coordinates via DRO

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#182]
It would have come in handy so many times.  :)

**Comment by petervanderwalt** [comment]
![image](https://user-images.githubusercontent.com/31449271/111357743-3eaffc00-8692-11eb-9d89-92786daa29b0.png)
Shift+Enter to Set entered coordinates as current work coordinates
Enter to Go to entered coordinates

**Comment by sharmstr** [comment]
Its like my bday!   I was working on this earlier today.  I like your solution much better.  THANK YOU!

**Comment by petervanderwalt** [comment]
Now I'm curious what your plan was? (:

**Comment by sharmstr** [comment]
A toggle similar to the jog toggle.  Lame.  LOL
