### ISSUE TITLE
Can we have a display of the actual feed rate?

### ISSUE THREAD

**Issue by JustinTimeToo** [OpenBuilds/OpenBuilds-CONTROL#183]
I'd like to have a display of the actual feed rate and see it change when I move the feed slider to show the current feed rate (not in percentage)

**Comment by petervanderwalt** [comment]
Added in v1.0.277 

![image](https://user-images.githubusercontent.com/31449271/106469751-5a778e00-64a8-11eb-80e3-fbebdf83f16a.png)

**Comment by sharmstr** [comment]
Hey Peter, this doesnt appear to be working.  I have a 2 hour job running right now so cant test, but I noticed it said 0mm/min at 100% so I changed it to 105% but it only shows the percentage difference(?).  I'm on .282

![20210203_112303](https://user-images.githubusercontent.com/5436091/106798298-a47c8300-6612-11eb-88ca-f00287e62208.jpg)

**Comment by sharmstr** [comment]
Just went back to the machine and even at 140% it shows 0mm/min with a blip up to 1mm/min every couple of seconds.

**Comment by petervanderwalt** [comment]
Thanks, will check!

**Comment by petervanderwalt** [comment]
Fixed in 1.0.283

**Comment by sharmstr** [comment]
Hey Peter.  This appears to be fixed and it working great.  Thank you.
