### ISSUE TITLE
BUG: In GRBL Setting Tab

### ISSUE THREAD

**Issue by idiydownunder** [OpenBuilds/OpenBuilds-CONTROL#194]
I have recently noticed that the option for setting $10 (Status report options, mask) doesn't the 3 value in the drop down. You can manually set it but if you come to this GRBL Setting tab to set other options it will through an error.

**Comment by petervanderwalt** [comment]
![image](https://user-images.githubusercontent.com/31449271/109338177-936c0e00-786e-11eb-88a9-b97cf1a41e52.png)

We maintain compatibility with the Grbl Wiki: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#10---status-report-mask
