### ISSUE TITLE
Job completion dialog pops up on Z+ jog using keyboard shortcut

### ISSUE THREAD

**Issue by evilc66** [OpenBuilds/OpenBuilds-CONTROL#195]
After getting in a bluetooth number pad to use as a jog pendant (totally awesome btw once you put custom labels on the keys), I have found that every time I press Z+ (page up) in incremental or continuous jog modes, the "job completion" dialog pops up with no time elapsed. Does the same on my primary keyboard. The GUI Z+ jog doesn't have the same issue.

**Comment by sharmstr** [comment]
I was able to reproduce this.  Check your keyboard shortcut settings.  I'm willing to bet that you have Run/Pause assigned to pageup as well as Z+.

Hey Peter,  I thought at one point Control looked for duplicate key assignments.  Maybe I'm thinking of macro key assignments.

**Comment by petervanderwalt** [comment]
Agreed, may be related to customized keys, default does not cause the issue. 

We don't check for duplicates (but i guess we should)

**Comment by petervanderwalt** [comment]
v1.0.291 and up will check for duplicates 

![image](https://user-images.githubusercontent.com/31449271/110642809-0f921a00-81bc-11eb-865a-504590f59e5f.png)

**Comment by evilc66** [comment]
Sorry for taking a while to get back to you guys.

Turns out I did have a duplicate key assigned to Run/Pause somehow. All fixed now.

**Comment by petervanderwalt** [comment]
Did away with the red toast error, now showing error right below key you are trying to assign: 
(also crosschecks internal key assignments, macros, etc to really cut down on accidental duplicates)

![image](https://user-images.githubusercontent.com/31449271/110680256-09fafb00-81e1-11eb-811d-ce28ce6d009c.png)

Should be out in a week or so
