### ISSUE TITLE
OpenBuilds CONTROL - maximizing the window on Ubuntu doesn't work as expected

### ISSUE THREAD

**Issue by WinVetPro** [OpenBuilds/OpenBuilds-CONTROL#198]
![grafik](https://user-images.githubusercontent.com/16663770/111284049-0b448180-8640-11eb-9605-6b028611deeb.png)

Doubleclicking the window title on Ubuntu doesn't maximize the window and overlaps the previous image.

**Comment by petervanderwalt** [comment]
We use https://www.electronjs.org/docs/api/browser-window - i see some notes about Linux not fully supporting maximising for Electron windows - unfortunately upstream from us. 

You could keep the window close (in systray) and open a Chromium instance to 127.0.0.1:3000 to avoid using the Electron window
