### ISSUE TITLE
Machine time doesnt make sense

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#207]
https://openbuilds.com/threads/interface-firmware-update.17161/#post-113548

![machinetime](https://user-images.githubusercontent.com/5436091/113042761-6aca8300-9150-11eb-85ea-446c42faab64.png)

**Comment by petervanderwalt** [comment]
Was fixed in v1.0.296, guess I should release it, I couldn't yet last week
