### ISSUE TITLE
Additional keyboard shortcuts.

### ISSUE THREAD

**Issue by theshortest** [OpenBuilds/OpenBuilds-CONTROL#209]
Hotkeys for zeroing  X, Y, Z and XYZ would be extremely helpful for gamepad/numpad controller.

**Comment by sharmstr** [comment]
Easy to do with macros.  I have a post about it here:  https://thayneco.com/set-zero-keyboard-shortcut-openbuilds-control/

**Comment by theshortest** [comment]
Well that's awesome. I don't know why I didn't think of that. I'm setting up a Antimicro Gamepad config. This is great!!
