### ISSUE TITLE
Job complete time and filename bugs

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#210]
@sharmstr reported two good ones https://openbuilds.com/threads/job-completed-popup-missing-in-1-0-298.17732/#post-114171

**Comment by petervanderwalt** [comment]
Path issue from files posted via the API: Fixed backend to stop including the full path
```
var filename = path.parse(filePath)
filename = filename.name + filename.ext
```
Also limited column width, thanks for the idea

**Comment by petervanderwalt** [comment]
Job timer:  Upon completing job, update to 

![image](https://user-images.githubusercontent.com/31449271/115028290-f8360300-9ec4-11eb-82f1-99a535803cc4.png)

**Comment by sharmstr** [comment]
I guess what confused me about the first time stamp and what it was for is because mine isnt updating while the job runs.

Also, just installed 299.  The job log isnt formatted and first time stamp doesnt say "done".  I did stop the job early.

![image](https://user-images.githubusercontent.com/5436091/115035458-72dd2f00-9e81-11eb-8bfb-41ee47bf0bfa.png)

**Comment by petervanderwalt** [comment]
I think there may be a Build issue, I downloaded the build, and indeed the changes are not included.  Incremented build number – pushing again, will download and test v1.0.300 before releasing

Sent from Mail for Windows 10

**Comment by sharmstr** [comment]
Getting closer.  The job log format is awesome.  Thank you.

But the first timestamp is still whacky

![image](https://user-images.githubusercontent.com/5436091/115054125-ba20eb00-9e94-11eb-9cca-07f45b4fc693.png)

**Comment by petervanderwalt** [comment]
> EDIT: Looks like this only happens when you stop a job before its done.

Could be! I do a cleanup when a job is complete.
