### ISSUE TITLE
Editing in DRO changes decimal to 2 places; keep 3 decimal places

### ISSUE THREAD

**Issue by brrian11** [OpenBuilds/OpenBuilds-CONTROL#216]
When editing in DRO, show three decimal places instead of two. See:

https://openbuilds.com/threads/editing-in-dro-changes-decimal-to-2-places.18006/#post-116502

**Comment by petervanderwalt** [comment]
Will fix in next release, good catch!

**Comment by petervanderwalt** [comment]
Fixed in 1.0.304, thanks for the report!
