### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by SeanDolan** [OpenBuilds/OpenBuilds-CONTROL#218]
I would really like the ability to enter a dark mode for the OpenBuilds Control Software in my browser. I have been able to replicate what I would like for the interface using a Google Chrome Extension, however the preview window doesn't look like it is able to be impacted by stylesheet changes by the extension.

I know this is not a priority but it would be awesome if there was a dark mode or even better if we could select colours for different components (e.g. preview window background, foreground and rulers).

Thank you for your time reading this request. I really appreciate your valuable time and efforts on this software.

**Comment by petervanderwalt** [comment]
I'll help you with some clues on playing with the ThreeJS code, but officially we won't consider adding a dark mode.  However, as you have your CSS and after this post, you can play with the ThreeJS code too, you can wrap all that into a Javascript Macro to share with the community too: 

So, the 3D view runs on https://threejs.org/ 

Checkout https://github.com/OpenBuilds/OpenBuilds-CONTROL/blob/master/app/js/viewer.js and https://github.com/OpenBuilds/OpenBuilds-CONTROL/blob/master/app/js/viewer-ruler.js to see how the viewer is drawn

From the JS Macro, you can access the Renderer and other objects, overwrite existing functions, etc to change whatever you want: Learn more about JS Macros here: https://openbuilds.com/threads/help-getting-started-with-javascript-macros-in-control.15880/#post-97234 and also https://thayneco.com/openbuilds-control-javascript-macros-getting-started/ 

For, for example, removing the "sky" and setting the Renderer Background, allows you to make the Background of the 3D view darker:

workspace.remove(sky);
renderer.setClearColor(0x333333, 1)

Example:
![image](https://user-images.githubusercontent.com/31449271/121363763-85329100-c937-11eb-8150-595284c78626.png)

Through those, into an Autorun JS macro, and it will do that on startup for you (:
You can get rid of the Chrome extension and use JQuery to setup the CSS as well: See https://www.w3schools.com/jquery/jquery_css.asp then you can use the Macro in the CONTROL UI as well. 

Closing this issue for now, but feel free to reply here with questions and sharing your work, happy to help you promote your JS Macro (;

**Comment by petervanderwalt** [comment]
![image](https://user-images.githubusercontent.com/31449271/121365598-12c2b080-c939-11eb-8bbe-55bb620f0742.png)

Wrap it in a setTimeout so that the renderer is up and ready when it executes (:

**Comment by petervanderwalt** [comment]
Updated:  One-liner Macro using CSS Filters:

```
$(':root').css("filter", "invert(1) hue-rotate(180deg) saturate(4)") 
```

Results in 

![image](https://user-images.githubusercontent.com/31449271/121573012-09af0d80-ca25-11eb-9bb4-ab09743af0c7.png)

**Comment by SeanDolan** [comment]
WOW! Above and beyond as always!  Thank you!
