### ISSUE TITLE
Check if machine is homed and if any G53 moves are in the GCODE, Ask to Home

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#219]

**Comment by petervanderwalt** [comment]
Check if machined is homed and if any G53 moves are in the GCODE, Ask to Home

**Comment by petervanderwalt** [comment]
From #224: suggested by @sharmst 

> we could do some trick messages in the probe wizards and warning messages when starting a job that changes to a different WCS other than the current WCS. Maybe tie that into your planned "check if homed and for G53" feature you have planned.

**Comment by petervanderwalt** [comment]
It does not, no

I was planning on setting a parameter in the 'status' object from index.js whenever $h passes through, and reset it to false on alarm, grbl init string, etc 

That way the UI can just reference the status - and will allow co-existence with jog widget (other web interfaces can send $h so best to check in index.js under node, rather than just in frontend)

**Comment by sharmstr** [comment]
Okay cool.  That's what I thought.  Was also trying to work out a way to tell if 'fake homing' was being used.  This info helps.

**Comment by petervanderwalt** [comment]
If there ever was a concept I want to ban to hell its fake homing.  Get the switches, just like, get the switches... its soooo cheap!

**Comment by petervanderwalt** [comment]
![image](https://user-images.githubusercontent.com/31449271/164542488-4d5aa507-1bc0-4bb9-99b8-59445282156c.png)

>V1.0.318 - lets test it out in the field with G53 first

**Comment by petervanderwalt** [comment]
Todo: Only popup Tip window if Homing is enabled in Grbl settings?
