### ISSUE TITLE
Circle problem

### ISSUE THREAD

**Issue by mohammadyzr** [OpenBuilds/OpenBuilds-CONTROL#220]
Hi. Thanks for your great software. I have a problem while milling circles that I created its gcode by Aspire:
<a href="https://freeimage.host/i/RW7Yve"><img src="https://iili.io/RW7Yve.md.jpg" alt="RW7Yve.md.jpg" border="0"></a>
<a href="https://freeimage.host/i/RW7ayu"><img src="https://iili.io/RW7ayu.md.jpg" alt="RW7ayu.md.jpg" border="0"></a>

**Comment by petervanderwalt** [comment]
Can only be Mechanical - CONTROL has no impact on machine moves
