### ISSUE TITLE
Documentation on creating application files.

### ISSUE THREAD

**Issue by rlwoodjr** [OpenBuilds/OpenBuilds-CONTROL#221]
I have mostly programmed in C and VBA.  I am trying to modify the code.  My question is:

**Is there documentation on creating the application files?**

I have downloaded and installed Visual Studio Code and node.js, and Live Server, but I do not know how to make the application files.  Any help would be appreciated.

**Comment by sharmstr** [comment]
There are a few forum discussions.  Here's one:  https://openbuilds.com/threads/build-openbuilds-control-from-source.14765/

**Comment by rlwoodjr** [comment]
Thanks. I appreciate your response.
