### ISSUE TITLE
Allow probing in other WCS systems as well

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#224]
https://openbuilds.com/threads/openbuilds-control-software.13121/page-66#post-120688

**Comment by sharmstr** [comment]
Along these lines, it would be nice to display current WCS.  Maybe in the space above setzero X button.  I tried to do this myself but couldnt figure out how to get the $G info back from grbl.  Thought it might be in laststatus.

Anyhow, not a must have for sure.  But if that info was available we could do some trick messages in the probe wizards and warning messages when starting a job that changes to a different WCS other than the current WCS.   Maybe tie that into your planned "check if homed and for G53" feature you have planned.

**Comment by petervanderwalt** [comment]
Updated G10 to P0 https://github.com/OpenBuilds/OpenBuilds-CONTROL/commit/55565617bb28d89cc8191d3be56a1f44812b652a up for testing as v1.0.306

**Comment by petervanderwalt** [comment]
> Along these lines, it would be nice to display current WCS. Maybe in the space above setzero X button. I tried to do this myself but couldnt figure out how to get the $G info back from grbl. Thought it might be in laststatus.
> 
> Anyhow, not a must have for sure. But if that info was available we could do some trick messages in the probe wizards and warning messages when starting a job that changes to a different WCS other than the current WCS. Maybe tie that into your planned "check if homed and for G53" feature you have planned.

Leaving ticket open - would be good to add it to the Parser from the backend side - I have done it for my old GrblJS host https://github.com/openhardwarecoza/grbljs/blob/master/index.js#L1090-L1258 so relatively easy to port 

In GrblJS I only request $G upon first connection, and when a G54-G59 is sent https://github.com/openhardwarecoza/grbljs/blob/master/index.js#L746-L751

**Comment by sharmstr** [comment]
Awesome!  

I'll do some probe testing here shortly.  Thanks!

**Comment by petervanderwalt** [comment]
Released (:

**Comment by petervanderwalt** [comment]
Comments? 

Sneaked a somewhat hidden little button up here

![image](https://user-images.githubusercontent.com/31449271/144295788-161a5029-167e-4c74-a657-6251bdf7a288.png)

Has a dropdown menu so you don't need to use the Console:

![image](https://user-images.githubusercontent.com/31449271/144295911-f38e44da-0560-46eb-944b-7ad9969e59e2.png)

And the parser picks up the coordinate system from $G and updates what's shown on the button (current state)

**Comment by sharmstr** [comment]
That's exactly what I was thinking.  I didnt want to push my luck by asking for it to switch WCS as well.  Whoop!

**Comment by petervanderwalt** [comment]
Made it a little prettier, and added the Checkmarks so you also see in the Menu where you are

![image](https://user-images.githubusercontent.com/31449271/144301044-bb4298b9-61a7-4cad-8217-867e141b22df.png)

Will be out as v1.0.308 (:

Now... someday when I have a week to work on it - we gotta add 3D view of the machine+work coordinates (just colored rects showing machine size (from Grbl Max travel) and relative work offsets (:

**Comment by petervanderwalt** [comment]
> In GrblJS I only request $G upon first connection, and when a G54-G59 is sent https://github.com/openhardwarecoza/grbljs/blob/master/index.js#L746-L751

This section introduced a bug, will fix today
When I wrote that for GrblJS it was still based off an older version of node-serialport - which handled the "realtime" command without interfering with the running stream - in the later versions of node-serialport used by CONTROL, it seems to
