### ISSUE TITLE
HTTPS Certificate on upload API has expired

### ISSUE THREAD

**Issue by harmanpa** [OpenBuilds/OpenBuilds-CONTROL#226]
The certificate on https://mymachine.openbuilds.com:3001/upload has expired. Sending a file to http://mymachine.openbuilds.com:3001/upload works via Postman, but I'm trying to send a blob from within the browser which will only send to HTTPS.

**Comment by petervanderwalt** [comment]
You must be running an out-of-date version of CONTROL:  v1.0.309 is current and it's cert still valid till 6th Jan
![image](https://user-images.githubusercontent.com/31449271/147154695-8e51f718-e97e-44f4-85d8-4c76c093212f.png)
