### ISSUE TITLE
Add z-index to #completeMsgModal

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#229]
Add a z-index value to #completeMsgModal so its always on top of other dialogs.  I'm working around it, but probably wouldnt hurt to have it in Control.

**Comment by petervanderwalt** [comment]
Added in v1.0.314 - let me know if you still have an issue

**Comment by petervanderwalt** [comment]
Nope I should have tested better (: that didn't work. Reverted in 1.0.317 - will revisit

**Comment by petervanderwalt** [comment]
Going through the older open ones, 2 years on is this still an issue for you?

**Comment by sharmstr** [comment]
I work around it by changing css with the macro, so no.
