### ISSUE TITLE
Tablet/touch improvement ideas (w. some code)

### ISSUE THREAD

**Issue by GhostNoteAudio** [OpenBuilds/OpenBuilds-CONTROL#233]
Hello. I wanted to raise awareness of a simple Javascript macro I've created, which adds a few usability changes to Openbuilds Control. I wanted to share this script with the developers, in case there are feature ideas or anything else you might find useful about it.

The macro is here: https://gist.github.com/GhostNoteAudio/6822c4b7c896ae0263a12ede59d64be2

Short summary of the changes it applies, and why I've needed/wanted them:

I use a Surface Pro 4 to run OpenBuilds. I like using the touch interface, but CONTROL can be fiddly to use and I often mis-clicked buttons which could cause crashes. There were also features I missed, and lots of unused screen real-estate that could be used for additional feedback to the operator. Here's a list of the changes the script applies:

- Display machine coordinates on screen - currently you can see this if you hover over the coordinate boxes, but I can't "hover" with a touch device. Also, I consider machine position to be rather critical information, every other control software I've used displays this, I think OpenBuilds should too.
- Add 0.01mm movement button - because sometimes you need more precision.
- Allow one click access to any movement mode by changing how the "continuous" button is displayed. With the default UI, switching from Continuous mode to, say 10mm mode, when previously I was using 1mm mode requires two click; now it can be done with one. 
- Display Macro buttons on the main toolbar (use labels to set sorting order). There's so much screen space wasted, why not show a select set of macros next to the sliders, then I can have direct access to both macros and the console or 3d view.
- Add 150% and 175% Zoom options for high DPI displays. There's no way of adjusting for high resolution displays. On 4K monitors everything is tiny unless you change the system-wide scaling. Adding zoom options is a pretty good feature.
- Add +-10% buttons to the Jog, Feed and Tool sliders. The sliders are TERRIBLE to interact with. They're terrible with a mouse, they're unusable with touch. So I added +-10% buttons to make it easier.
- Increase the size of the reset speed buttons. Because why are they so small? If you've increased the speed, you might find you suddenly need to reset it, so you want big buttons that are easy to hit.
- Remove useless stuff from the Open Menu. - OK sorry I know this is sponsored content or whatever, but nobody uses anything other than the "Open GCode" option :) - so I remove the others, and also make the menu bigger, for easier selecting.

I hope some of these changes might make it into future versions of the software. In any case, I hope my user feedback is helpful :)

**Comment by petervanderwalt** [comment]
Community macros are shared in https://openbuilds.com/threads/getting-started-with-javascript-macros-in-control-library-of-macros-created-by-the-community.15880/
