### ISSUE TITLE
On disconnect, reset status:{} to some cleaner, saner defaults

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#244]
As per @sharmstr suggestion:

"I think what threw me off is that its not setting the DROs back to 0 when it disconnects"

**Comment by sharmstr** [comment]
To be clear, I was talking about my new DROs.   Yours do set back to 0.00 when status equals 0 or 6.

**Comment by petervanderwalt** [comment]
Ahh OK! but will keep it open and just look it all over, make sure I didn't miss anything - or that I am doing it right (in status{} not in like a weird ui.js way perhaps)
