### ISSUE TITLE
Install broke

### ISSUE THREAD

**Issue by JiMcNulty** [OpenBuilds/OpenBuilds-CONTROL#251]
The install broke, seems like the same issues I had with the latest electron build...something is up 
You can view the relevent issue here:
https://github.com/electron/electron/issues/35193

`⠸ Building module: bindings, Completed: 0make: Entering directory 'OpenBuilds-CONTROL/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
⠦ Building module: bindings, Completed: 0In file included from.electron-gyp/9.4.4/include/node/node.h:63,
                 from ../../../nan/nan.h:60,
                 from ../src/./serialport.h:13,
                 from ../src/serialport.cpp:1:
.electron-gyp/9.4.4/include/node/v8.h:9116:75: warning: ‘v8::MicrotasksCompletedCallback’ is deprecated: Use *WithData version. [-Wdeprecated-declarations]
 9116 |   void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
      |                                                                           ^
.electron-gyp/9.4.4/include/node/v8.h:7345:16: note: declared here
 7345 | typedef void (*MicrotasksCompletedCallback)(Isolate*);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
.electron-gyp/9.4.4/include/node/v8.h:9124:78: warning: ‘v8::MicrotasksCompletedCallback’ is deprecated: Use *WithData version. [-Wdeprecated-declarations]
`

**Comment by petervanderwalt** [comment]
Works fine for us, unfortunately we cannot provide developer assistance.  If you cannot resolve compile issues, rather use the precompiled releases: https://github.com/OpenBuilds/OpenBuilds-CONTROL/releases
