### ISSUE TITLE
No way to connect via wifi on FluidNC

### ISSUE THREAD

**Issue by ewidance** [OpenBuilds/OpenBuilds-CONTROL#252]
I could not find a way to connect via websockets on FluidNC. Is this planned for a future release?

**Comment by petervanderwalt** [comment]
CONTROL is for use with Grbl 1.1 from https://github.com/gnea/grbl/wiki/ only. It does not support other firmwares

**Comment by viernullvier** [comment]
For the record: FluidNC appears to be supported now - I was able to establish a wifi connection (tested with v1.0.360).

**Comment by petervanderwalt** [comment]
> For the record: FluidNC appears to be supported now - I was able to establish a wifi connection (tested with v1.0.360).

Partially supported. Still work in progress

See https://github.com/OpenBuilds/OpenBuilds-CONTROL/issues/283 some things are NOT working yet (:
