### ISSUE TITLE
3d View doesnt display 360 g2/g3 moves

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#257]
Per report:  https://openbuilds.com/threads/openbuilds-control-software.13121/page-72#post-128262

No arc errors in console.

; Generated by Jog Recorder on 2022-09-14

G54 ; Work Coordinates
G21; mm-mode
G90; Absolute positioning
S1000 M3; Spindle on
G4 P1.8

G0 X30 Y25 Z0.00
G0 X10 Y25
G2 F700 X10 Y25 I20.00 J0 ; 

![image](https://user-images.githubusercontent.com/5436091/190227047-99a153d6-64ea-475c-bd4f-8e55f6307586.png)

**Comment by sharmstr** [comment]
If I change out the g2 with a g3 above, the code works.  So seems to only be an issue with G2

**Comment by petervanderwalt** [comment]
Please test that this did not break arcs for other gcode :)
