### ISSUE TITLE
High CPU load with just opening to GUI

### ISSUE THREAD

**Issue by JiMcNulty** [OpenBuilds/OpenBuilds-CONTROL#258]
![image](https://user-images.githubusercontent.com/6442378/190352425-1c239bb9-497f-468a-a29e-100a4862b8d1.png)

I know, its PI, not supported and such
But just reporting so you would know...

**Comment by petervanderwalt** [comment]
Troubleshooting tab > Application Diagnostics > Disable High CPU users like the 3D view etc.

**Comment by JiMcNulty** [comment]
> Troubleshooting tab > Application Diagnostics > Disable High CPU users like the 3D view etc.

Thanks, It helped a little but the CPU usage is still unreasonably high (gui is idle, no file is open, fkms enabled):
![image](https://user-images.githubusercontent.com/6442378/191775344-c4840b22-f2c8-453d-8eb0-2623880c02c4.png)


For example, this is the CPU usage with an open chromium on youtube:
![image](https://user-images.githubusercontent.com/6442378/191775110-669837fc-05d9-4567-8203-80ea8bd04739.png)


Something else is going on I guess...

**Comment by petervanderwalt** [comment]
![image](https://user-images.githubusercontent.com/31449271/192341753-0e54d4d0-b749-4286-88f2-90e45c77af00.png)

**Comment by JiMcNulty** [comment]
> ![image](https://user-images.githubusercontent.com/31449271/192341753-0e54d4d0-b749-4286-88f2-90e45c77af00.png)
Man come on you know that your comment is not helping
We are talking about linux on a PI 4B 8GB with 3D drawing disabled....

**Comment by petervanderwalt** [comment]
> PI 4B

Well, that's not officially supported, so please don't even open issues for Pi please. See https://github.com/OpenBuilds/OpenBuilds-CONTROL/wiki/Installing-on-Pi4 and the bold note right at the top there.

**Comment by JiMcNulty** [comment]
> I know, its PI, not supported and such But just reporting so you would know...

So ya... 
You should value more users who take the time to report stuff to try to try and help
