### ISSUE TITLE
Bug; Flattening Wizard doesnt start at 0.0.0 but at 1/2 bit diameter offset

### ISSUE THREAD

**Issue by ImagineerNL** [OpenBuilds/OpenBuilds-CONTROL#259]
According to the image in the wizard, the flattening job should start at 0.0.0;
But the job actually starts at half the bit diameter offset on both X and Y; in my example, at X17.5 / Y 17.5 for a 35mm flattening bit 

![image](https://user-images.githubusercontent.com/62603552/190430480-f0e209ec-7e06-4d0e-996b-d7b2ce1db964.png)

![image](https://user-images.githubusercontent.com/62603552/190430665-ecea6fa4-5af6-4fd8-be77-99e7cb579e77.png)

I would expect it to start at 0.0.0, so my spoilboard is flattened 17.5mm wider than my max workspace.

**Comment by sharmstr** [comment]
Its not a bug.  That's by design:  https://openbuilds.com/threads/what-happened-here-spoilboard-surface-fail.16704/#post-104823

**Comment by ImagineerNL** [comment]
Well, that still means the design is not matching the image in the wizard.
The 0.0.0 is clearyl at the center of the bit.

![image](https://user-images.githubusercontent.com/62603552/190449024-40691708-4022-4e5f-9227-c53f9039dcb2.png)

I did try and compensate for the size of the bit and make the X and Y 35mm wider, but that still offsets it from my 0.
And i can not compensate to go -17.5 in my work offsets, because that triggers the alarms.
Please explain how i should compensate for it to actually start at 0.0.0 and not on 17.5 ,17.5, 0
My CNC work area is only X: 530mm by Y: 740mm so every cm i am able to use is worth it for me.

**Comment by sharmstr** [comment]
After its done surfacing, move your bit to 0,0,(whatever your skim depth is) and jog to complete a framing pass.  That's what I do anyways.

**Comment by ImagineerNL** [comment]
Thats indeed a good workaround, thanks.

Does render a bit of the 'wizard' not so 'wizard' though if it still requires extra manual work

**Comment by sharmstr** [comment]
Well because of the way you and I want to use it.  A lot of people want a clean and square edge to line their stock up against :)
