### ISSUE TITLE
How build

### ISSUE THREAD

**Issue by GogoLike** [OpenBuilds/OpenBuilds-CONTROL#263]
Hello, pls create build source manual. I need hight-map functional and merge old fork to actual software version, but i can't build it.

**Comment by petervanderwalt** [comment]
We don't really compile locally - we make use of GitHub Actions to do that for us: https://github.com/OpenBuilds/OpenBuilds-CONTROL/blob/master/.github/workflows/build.yml 

If you want to build locally, familiarise yourself with Node/Electron/Electron-Builder - pretty standard stuff and well documented under their relevant projects
