### ISSUE TITLE
Q: How to contribute to the Wiki?

### ISSUE THREAD

**Issue by poWer4aiX** [OpenBuilds/OpenBuilds-CONTROL#266]
I might be a fool, but how to contribute to the Wiki? I would like to bring some light into how to build the software from scratch. I see that I can clone it locally, but this seems not to be linked to the original repo...

I can also contribute to the README.md, but I guess the Wiki is a better place.

**Comment by petervanderwalt** [comment]
I'm not sure, but does https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages work for you?

Just keep in mind content may be moderated to comply with OpenBuilds internal/external policies and requirements.

**Comment by poWer4aiX** [comment]
This is the explanation on how to maintain a Wiki, where you have write access to. I don't know on which levels you can define who can directly contribute to the Wiki. Of course, opening it for the world is not an option.

One option might be to add a separate repo which holds a copy of the wiki pages. This enables us to fork and contribute. But I don't know how to syncing the repo then with the wiki...

**Comment by poWer4aiX** [comment]
Next option might be to stick with .md files in the main repo...

**Comment by petervanderwalt** [comment]
Yeah unfortunately they don't provide more granular control it seems:

![image](https://user-images.githubusercontent.com/31449271/199331096-b11cfaa1-6935-49e6-928d-3ab84c70c177.png)


Either public, or full push priviledge.  

I guess submitting in an Issue is an option - it understands Markdown
