### ISSUE TITLE
Cannot Change IP in Grbl Settings

### ISSUE THREAD

**Issue by kingsplace** [OpenBuilds/OpenBuilds-CONTROL#274]
when i change any ip settings in the grbl Settings page i cannot press save firmware it stays greyed out

Edit: just noticed when you first change it to 192.167.x.x then save it and then put in the right 192.168.x.x save it. it works! some small bug?

**Comment by petervanderwalt** [comment]
Small bug confirmed, thanks for the report (:

**Comment by petervanderwalt** [comment]
Fixed in v1..338 and later - thanks again. Let us know if you find other bugs (:
