### ISSUE TITLE
Bug: Probe queue stuck

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#277]
https://openbuilds.com/threads/blackbox-x32.19810/#post-129926 relates
Bug confirmed, queue gets stuck after sending G38.2. 
Works with Grbl 1.1 
ForceQueue gets it moving, but the clearance jog does not move away

**Comment by petervanderwalt** [comment]
@terjeio - hoping I may be able to bug you for a little advice on this one - seems to be something we need to handle differently for grblHAL. 

Little background:  We've been using the Character counting method outlined in the Grbl 1.1 > Interface wiki for several years now, without issue with Grbl.   Making CONTROL work with grblHAL, we've located something that doesn't work the same as Grbl did.  In CONTROL we use the "run a job" code for a lot of things other than jobs.  Any task thats multiple gcode lines gets run "as a job" - this includes Grbl Settings (changed a little in later updates) (footnote 1), Macros, Probe routines etc.  We assemble the lines, split with a newline "\n" - CONTROL splits it up when it finds a newline, sends that line (appends a Newline back onto it as Grbl expected it to) to the firmware.  

With grblHAL this method seems to fail, if one of the commands fall in a certain category.  For example, if we load a Grbl settings dump as a job ($key=val\n$key2=val\n, etc) it looks like the serial queue gets corrupted (as if grblHAL dropped chars while it was doing a flash write?) 

We're also seeing this behaviour (almost similar) with Probing when we send something like 

```
G21
G10 P0 L20 Z0
G38.2 Z-25 F100
G4 P0.4
G10 P0 L20 Z10
```

It executes the G21, it executes the G10,  The G38 gets sent (confirmed that it is sent out the Serial port) but grblHAL does not start the probing routine. 

If I inject an extra Newline after the G38 - it starts probing as normal.  But I cannot append this newline in the same send (makes no difference) - I have to add a couple milliseconds delay before sending it.  Wild and crazy theory, but almost feels like while its busy storing the offsets to flash "eeprom" from the G10, something is happening oddly with the next commands in queue. 

Now that said, I did do a sanity check with ioSender and cannot replicate it - but I have not dug in to see what ioSender does under the bonnet.   

CONTROL never had this issue (nor still does not) with Grbl - so I don't believe its an outright bug on our end - but I am totally sure its something we aren't thinking of, that we need to do just a little differently for grblHAL? Appreciating your thoughts on this (: 

Footnote 1:  Grbl Settings - leading up to release date we changed the UI to have a progressbar when saving Grbl Settings so we are now sending over line-by-line instead of running it like a job - didn't do more debugging at the time, but similar to the Probing example above - adding a delay helped prevent the issue from appearing - and feels similar (setting writing to eeprom, perhaps causing some issue with queue)

**Comment by terjeio** [comment]
Ideally settings should be stored in EEPROM or FRAM, not flash...

grblHAL buffers writes to non-volatile storage (NVS) and only flush this buffer when [certain conditions are met](https://github.com/grblHAL/core/blob/d10804433c2b1060bb8ad6c5fa04218c2cf435a8/protocol.c#L392-L395), one is when not in "file run" mode. ioSender uses "file run" mode when writing settings, this is entered and exited by delimiting the transaction with lines containing the % character - ensuring that all changed settings are written to NVS in one go. See the _settings.txt_ file written to the installation directory when a backup is written from the _Settings: Grbl_ tab in ioSender.

>  Wild and crazy theory, but almost feels like while its busy storing the offsets to flash "eeprom" from the G10, something is happening oddly with the next commands in queue.

I see that I have disabled processing real-time commands (by ditching them) during ESP32 flash writes in order to avoid panics. And there is a [bug that incorrectly filters out LF characters](https://github.com/grblHAL/ESP32/blob/e0cfb81af19c426d545eae19b35c7ca2f897dbf0/main/nvs.c#L37) when it should not. Correct code is:

`static const DRAM_ATTR char ESP_LF = ASCII_LF;`
 
Hopefully that will fix the G10 issue,

**Comment by petervanderwalt** [comment]
> Ideally settings should be stored in EEPROM or FRAM, not flash...

(: Didn't check what you use for the ESP32 driver, but you know what I mean 



> I see that I have disabled processing real-time commands (by ditching them) during ESP32 flash writes in order to avoid panics. And there is a [bug that incorrectly filters out LF characters](https://github.com/grblHAL/ESP32/blob/e0cfb81af19c426d545eae19b35c7ca2f897dbf0/main/nvs.c#L37) when it should not. Correct code is:
> 
> `static const DRAM_ATTR char ESP_LF = ASCII_LF;`
> 
> Hopefully that will fix the G10 issue,

Thanks! Will test it today! (: 

> % character - ensuring that all changed settings are written to NVS in one go. See the _settings.txt_ file written to the installation directory when a backup is written from the _Settings: Grbl_ tab in ioSender.

Good solution, will investigate that as well to make sure we do it more by the book

Thanks for your time!

**Comment by petervanderwalt** [comment]
> I see that I have disabled processing real-time commands (by ditching them) during ESP32 flash writes in order to avoid panics. And there is a [bug that incorrectly filters out LF characters](https://github.com/grblHAL/ESP32/blob/e0cfb81af19c426d545eae19b35c7ca2f897dbf0/main/nvs.c#L37) when it should not. Correct code is:
> 
> `static const DRAM_ATTR char ESP_LF = ASCII_LF;`
> 
> Hopefully that will fix the G10 issue,

Fantastic, that worked a treat, you can apply it upstream (:

**Comment by petervanderwalt** [comment]
Resolution: Update firmware on BlackBox X32 as per https://docs.openbuilds.com/doku.php?id=docs:blackbox-x32:firmware

**Comment by MickyPf** [comment]
Unfortunately the update doesn't work for me. After the update, the second Y motor no longer runs. Since I also have the problem with the Z-Probe, I would like a solution.

**Comment by petervanderwalt** [comment]
> Unfortunately the update doesn't work for me. After the update, the second Y motor no longer runs. Since I also have the problem with the Z-Probe, I would like a solution.

For normal support, please make use of our forums. In particular, refer to https://openbuilds.com/threads/blackbox-x32-y2-motor-not-working.19868/#post-130192

**Comment by MickyPf** [comment]
Thank You
