### ISSUE TITLE
Homing and Z-probing missing on mobile client

### ISSUE THREAD

**Issue by qbotas** [OpenBuilds/OpenBuilds-CONTROL#281]
It would be very nice to be able to use Z-probe without need to reach the computer. 
Same for homing.

**Comment by petervanderwalt** [comment]
Appreciate the thought for sure - thank you. There is a revamp of the Job widget on the cards, but mainly it is a "jog" tool. 

As a sidenote, checkout the OpenBuilds Interface:   Has Probing, Homing, etc

https://www.youtube.com/watch?v=DMz4ltP9Fm0
