### ISSUE TITLE
'Go X0 (Work Coord)' button

### ISSUE THREAD

**Issue by that-jim** [OpenBuilds/OpenBuilds-CONTROL#286]
The dropdown buttons on the DRO for sending the machine to zero use a command like 'G0 X0', this only seems to work if has had a previous command with G90. If the previous command was G91 then the machine does nothing. Maybe it should send 'G90 G0 X0'.

Thanks for all your work on openbuilds control I do really like the software!

**Comment by petervanderwalt** [comment]
Yes it is best to assert modes we need, you aren't wrong. Funny this one hasn't popped up yet in all these years. Will get it fixed in next update

**Comment by petervanderwalt** [comment]
X, Y, Z all updated to send G90\nG21\n as well - please test V1.0.343 to be released later today
