### ISSUE TITLE
Auto level

### ISSUE THREAD

**Issue by beckmx** [OpenBuilds/OpenBuilds-CONTROL#297]
Hello guys, I was looking around the IDE, I was wondering if there is any auto-level feature, like a map to heights to react on the material shape

**Comment by sharmstr** [comment]
Short answer is no.  

Long answer: 

Someone posted a pull request a long time ago.  Discussion is here:  https://openbuilds.com/threads/can-add-fuction-auto-level-from-chilipeppr-widget-autolevel-in-software.19711/

Pull request is here:  https://github.com/OpenBuilds/OpenBuilds-CONTROL/pull/110

**Comment by Guenni75** [comment]
The most important engraving tool will never come for openbuilds? that sucks!
I guess I'll have to stay with bcnc then.
