### ISSUE TITLE
[FR] Add sort order to Macro's

### ISSUE THREAD

**Issue by ImagineerNL** [OpenBuilds/OpenBuilds-CONTROL#300]
Since using Openbuilds control I keep growing my Macro collection.
Unfortunately I don't find a  way to sort them, other than just deleting and adding them in the correct order.

A really simple sorting route could be to add an index number which can be editted in the macro config.
(and a pro tip to using it; start with index 10, 20, 30 etc so you have room to insert items in between ;) )
I'm even there's already some kind of index to which it currently loads the macro's; it just doesnt show them

This would greatly help in tidying up my macro screen.

**Comment by sharmstr** [comment]
" there's already some kind of index to which it currently loads the macro's; it just doesnt show them"

That index changes when macros are deleted so its not a reliable way to id a macro.  Example

0:  Macro 1
1:  Macro 2
2:  Macro 3

delete Macro 2

0: Macro 1
1: Macro 3

I started working on a javascript macro that would allow me to classify and arrange macros.  I'll dig up the code this week and see if I cant get something working.

**Comment by petervanderwalt** [comment]
We have those nice Move Up or Move Down sort on the toolpaths in OpenBuilds CAM https://github.com/OpenBuilds/OpenBuilds-CAM/blob/697ad358d74c7af901b9444666a846f4fdaa9b53/js/advanced-cam-tree.js#L7 that is easier to understand than the "typing in a new index number". Probably something like hiding up/down buttons but can enable from Wizards and Tools > Macros > Enable Sorting

**Comment by sharmstr** [comment]
Yes.  I was looking a that metroui list sort stuff.  Totally forgot about the one in CAM.  That should make it easier.

**Comment by petervanderwalt** [comment]
> Wizards and Tools > Macros

Reminder to self, that new menu can hold the long-overdue menu entries for https://github.com/OpenBuilds/OpenBuilds-CONTROL/issues/93

**Comment by petervanderwalt** [comment]
Any objection against removing the corner-gear-button edit, and replacing all this with Right-click context menu on each button? 

![image](https://user-images.githubusercontent.com/31449271/223195526-febe9f5c-d407-4d6f-9afd-632da47beada.png)

**Comment by petervanderwalt** [comment]
(and up vs down - or left vs right?)

**Comment by petervanderwalt** [comment]
Slated for V1.0.356 - closing issue - but feel free to comment (I did change the arrows to be left/right not up/down already since the screenshot!)

**Comment by sharmstr** [comment]
Getting rid of the gear icon pleases me :)

**Comment by petervanderwalt** [comment]
> No objection as long as its clear to use.

can bet you we'll have a couple old users saying "where the gear gone to" and a couple that can't figure out to right click on the button (which feels instinctive to me)

**Comment by petervanderwalt** [comment]
> I'd prefer left vs right, as thats how they currently flow and overflow to the next row.

![image](https://user-images.githubusercontent.com/31449271/223198430-fd6dd544-3942-4f98-ba64-2d5c0b81f0e8.png)

**Comment by sharmstr** [comment]
I have about 15 macros.  Upload the code if you want me to test it out.  I think my only concern is touchscreens.

**Comment by petervanderwalt** [comment]
Touch: Shouldnt hold = rightclick event? (not using custom events, using onContext: https://www.w3schools.com/jsref/event_oncontextmenu.asp

**Comment by sharmstr** [comment]
Yes it should.

**Comment by sharmstr** [comment]
I tried to brake it and couldnt.  Great job!

**Comment by petervanderwalt** [comment]
Hope you get (or already got) well soon! Thanks again for the suggestion!
