### ISSUE TITLE
error 36- there are unused left over g-code words arent used by any commands

### ISSUE THREAD

**Issue by Majormakes** [OpenBuilds/OpenBuilds-CONTROL#307]
![grbl error 36](https://user-images.githubusercontent.com/129928517/230241016-0a9e972b-92ec-4df7-b247-ffdcb7212e0c.PNG)

**Comment by petervanderwalt** [comment]
Not grbl compatible gcode.  S word should go with M3 commands, not in line with G1/2/3 
Make use of the correct CAM/Posts to resolve, and please note that the Github Issues are for real bugs, not support

Have a read through https://docs.openbuilds.com/doku.php?id=docs:software:overview
