### ISSUE TITLE
Feature Request: Remember COM port

### ISSUE THREAD

**Issue by ImagineerNL** [OpenBuilds/OpenBuilds-CONTROL#308]
For some reason, Openbuilds Control defaults to COM5 and i manually have to select the correct COM port (FTDI USB to serial COM3)

It's a small QOL feature, but much appreciated would be to (optionally?) remember the last connected COM port.

![image](https://user-images.githubusercontent.com/62603552/230732699-2ccee7b8-5c53-41e1-9d82-40bfaa9effd8.png)

**Comment by petervanderwalt** [comment]
https://github.com/OpenBuilds/OpenBuilds-CONTROL/commit/358b86d83857032b706f299a741d9d6807f9d574#commitcomment-140708021
