### ISSUE TITLE
add more incremental steps for jog.

### ISSUE THREAD

**Issue by pachucristo** [OpenBuilds/OpenBuilds-CONTROL#309]
i'm working with some pieces that I need to set the origin right at the center. and for that I cant use probe because i'm with a xpro v5 firmware that disable probe for an extra Y motor limit switch.

i'm using a comparator mounted on the spindle rotor to indicate the exact center, but when i'm off by +-0.1mm, I cant move the the axis in small enough steps with the buttons without overshooting the reading. 
Currently i'm just entering manualy the numbers incrementaly to the DRO(0.11-enter, check. 0.12-enter check...) and that works just fine but is very tedius. And I was thinking that would be useful to have more finer resolutions for moving the machine, directly from the user interface, or at least have the posibility to change the default values of the incremental jog buttons.

thanks to all people involved!!

**Comment by sharmstr** [comment]
Add a macros for you the distance and directions you want to move and assign keyboard shortcuts to them.

Example for moving .01mm in X+
$J=G91G21X0.01F1000

Example for moving .01mm X-
$J=G91G21X-0.10F1000
