### ISSUE TITLE
Turn off ads

### ISSUE THREAD

**Issue by UnCorpuscler** [OpenBuilds/OpenBuilds-CONTROL#310]
I own a blackbox as part of the lead machine. Super frustrating to spend all this money and having to get redirected to my browser every time I use the software. Come on.....

**Comment by petervanderwalt** [comment]
CONTROL doesn't redirect you to the browser? Unless YOU click the Ad (: which is easy, just don't
There is no extra time. The splash screen unloads when all the background stuff (bindings, socket.io, threejs, etc) has run their coarse
