### ISSUE TITLE
Persistent invalid port error on connection via Bluetooth after latest update.

### ISSUE THREAD

**Issue by Emmanuel-Ayegba** [OpenBuilds/OpenBuilds-CONTROL#319]
I updated to the latest version and my machine began malfunctioning. 
It has worked flawlessly via Bluetooth previously but now it connects for a while and reports invalid port.
Restarting the computer did not correct the error.
GRBL1.1f.

**Comment by petervanderwalt** [comment]
> I updated to the latest version and my machine began malfunctioning. It has worked flawlessly via Bluetooth previously but now it connects for a while and reports invalid port. Restarting the computer did not correct the error. GRBL1.1f.

Screenshot showing CONTROL window on Serial log tab after error occurred please
