### ISSUE TITLE
Probe

### ISSUE THREAD

**Issue by housspin** [OpenBuilds/OpenBuilds-CONTROL#320]
Just got the X32 and the interface, setup both and i have some issues
I cant use the probe with the interface, get an error.
![probe1](https://github.com/OpenBuilds/OpenBuilds-CONTROL/assets/13398567/57b870a9-24f7-4cec-b173-02e924c55628)
![probe](https://github.com/OpenBuilds/OpenBuilds-CONTROL/assets/13398567/407c18b7-13f8-47f1-a8c3-7750b909ae90)

Thank you in advanced

**Comment by housspin** [comment]
any idea? Thank you in advance.

**Comment by petervanderwalt** [comment]
Checkout openbuilds.com/forums for technical support. Github is for bugs/development

Probe file not found = skipped Prepare USB step in Interface Documentation

Inverted probe state = forgot to load machine profile, or wiring incorrect, or spindle has a Ground loop fault

**Comment by housspin** [comment]
Thank you so much
Regards
Housspin

**Comment by housspin** [comment]
Hi, OpenBuilds
Just purchased a VFD/spindle 1.5k air cooling system, and I need help to
connect the VFD to the Blackbox 32, i assume that with the VFD I can
control the Spindle via Blackbox32, any suggestions?
Thank you so much
Regards
Raul

**Comment by petervanderwalt** [comment]
> Checkout openbuilds.com/forums for technical support. Github is for bugs/development

Checkout openbuilds.com/forums for technical support. Github is for bugs/development
