### ISSUE TITLE
Move Macros Issue with > 9 Macros

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#323]
Hey Peter, 
There's an issue with moving macros when there is more than 9 of them.  Instead of moving the macro it will duplicate it.

Check out the following video.

https://youtu.be/f7QdChPJMVs

**Comment by petervanderwalt** [comment]
Good catch, weird one, I don't see anything obvious in the sorting code. Does it affect just the rendering, or also the stored macros in localStorage (Does an F5 refresh fix it?)

**Comment by sharmstr** [comment]
It gets stored.  Wish I had time to dig into it.  As usual it really only effects me.  LOL.  Just leave this open and one of us will get to it eventually. 

Might have something to do with alpha sorting instead of numeric?   idk

**Comment by sharmstr** [comment]
My guess was right.  Its a alpha sorting issue.  

In sortMacros functions, change

var indexes = [index, newIndex].sort(); //Sort the indixes

to 

var indexes = [index, newIndex].sort((a,b)=>a-b); //Sort the indixes

**Comment by petervanderwalt** [comment]
opened so I remember to apply, thanks for finding the fix
