### ISSUE TITLE
Tool Off Button does not work after stopping or aborting a job

### ISSUE THREAD

**Issue by Robotopera** [OpenBuilds/OpenBuilds-CONTROL#329]
Blackbox X32, Win 11, Latest Build

Stopping a job or aborting a job, doesn't seem to turn the tools off.  
Clicking the Tool Off button is also unresponsive. 
Clicking Tools On and then clicking Tools Off does work.

**Comment by Robotopera** [comment]
Tool is an routER11 connected to [an IOT Switch](https://openbuildspartstore.com/iot-switching-relay-power-strip/) via the tool port on the x32.

**Comment by petervanderwalt** [comment]
If issue still persists, that was a firmware bug. Updating grblHAL should resolve
