### ISSUE TITLE
Fail to update firmware under linux

### ISSUE THREAD

**Issue by ninao-xyz** [OpenBuilds/OpenBuilds-CONTROL#334]
Open builds control v1.0.370 is failing to update the firmware under Linux, it gets disconnected as soon it tries. Tried with appimage and the deb package. I'm using Ubuntu 22.04.3 LTS. Since I don't have any computer at home with windows, I had to beg a friend for his windows laptop to update the firmware. 
Note: found someone in openbuilds forums with the same problem.

**Comment by petervanderwalt** [comment]
Check user permissions (dialout group, etc) to allow user access to port, and check Python availability.  Best guesses without logs, screenshots or other advantageous info to help from.
