### ISSUE TITLE
Keyboard shortcuts:  Handle MetroUI naming non-standards of some keys in Macros

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#335]
Macro keyboard shortcuts dont take into consideration MetroUI naming conventions.  For example, Control will correctly change arrowright to right when saving the macro.  But when you press right, it doesnt do the conversion from arrowright to right.  You'll get the "Macro not found for arrowright" error.

Obviously not a big deal since I'm probably the only one to come across this.  :)

**Comment by sharmstr** [comment]
But when you click right, its not printing out 'test' to the console.   You're getting an 'undefined' message.

**Comment by sharmstr** [comment]
Not sure its the best place to fix it, but the searchMacro function doesnt match any of the special metro names.

`function searchMacro(prop, nameKey, myArray) {
  console.log(nameKey, prop, myArray)
  for (var i = 0; i < myArray.length; i++) {
    if (myArray[i][prop] === nameKey) {
      return myArray[i];
    }
  }
}`

For instance, nameKey will come be arrowright, but in the macro its right.  So it will never run the macro.

As a test, this works

`function searchMacro(prop, nameKey, myArray) {
  console.log(nameKey, prop, myArray)
  
  if (nameKey.toLowerCase() == 'arrowright') {
    nameKey = 'right';
  }
  for (var i = 0; i < myArray.length; i++) {
    if (myArray[i][prop] === nameKey) {
      return myArray[i];
    }
  }
}`

![image](https://github.com/OpenBuilds/OpenBuilds-CONTROL/assets/5436091/0d8d491e-fd9d-42cc-8f86-fd25c34e44c1)

**Comment by petervanderwalt** [comment]
Ahhhh now I see, sorry!

**Comment by petervanderwalt** [comment]
Was already doing some of the conversion (alt/ctrl/shift) in keyboard.js https://github.com/OpenBuilds/OpenBuilds-CONTROL/commit/562da2f706e2a8869a2cf2614ca29bbaa7826d60#diff-e52cb2231950cdf92d7ef8b5c835919016ded13ae8bf679aac910c306d744147L135 
so borrowed https://github.com/OpenBuilds/OpenBuilds-CONTROL/blob/master/app/js/macros.js#L285-L302 and added it to the section in keyboard.js 

![image](https://github.com/OpenBuilds/OpenBuilds-CONTROL/assets/31449271/3c61f1b3-b866-4df0-937e-bf0183ebda35)

**Comment by sharmstr** [comment]
I did see that, but for some reason I thought it was in the bindKeys function and just wasnt working. Sorry I didnt catch that earlier. Thank you for the fix.
