### ISSUE TITLE
Unable to flash firmware on OpenBuilds Control on Linux (EROFS: read-only file system)

### ISSUE THREAD

**Issue by dheera** [OpenBuilds/OpenBuilds-CONTROL#337]
![螢幕快照 2023-11-14 07-08-00](https://github.com/OpenBuilds/OpenBuilds-CONTROL/assets/1786477/ef4e4a36-c839-4a73-bba4-1edc08b5da76)

**Comment by petervanderwalt** [comment]
Try the DEB version instead of the AppImage
