### ISSUE TITLE
Re-Orient GUI view

### ISSUE THREAD

**Issue by Thimet1** [OpenBuilds/OpenBuilds-CONTROL#342]
Love the OpenBuilds CONTROL software. Is it possible to re-orient or re-organize the Screen layout to move or resize items? It would be very nice to increase the height of the Progress/path visual scene? Possibly by decreasing the size of the Over-ride sliders to make more room for the viewer off to the Righthand side of the screen.

**Comment by petervanderwalt** [comment]
Not at this time, and not planned, sorry
