### ISSUE TITLE
[request] Abort on disconnect, and/or ABORT button must be present always even not connected

### ISSUE THREAD

**Issue by jorgerobles** [OpenBuilds/OpenBuilds-CONTROL#360]
Rationale:
* Just happened that, running a job, that had to push the alarmbutton. The machine shuts down, but once switched on and press connect, Control software resumed sending GCODE.

Request:
* When driving a tethered job, if in any case the machine is disconnected the running job should be aborted.
Alternatively, Abort button SHOULD be visible even the machine is disconnected. (Aborting job, cleaning the buffer, etc.)

**Comment by petervanderwalt** [comment]
Wow! Long time, glad to hear from you @jorgerobles!

Solid suggestions! Thanks
