### ISSUE TITLE
Question - possible to port CONTROL to NeutralinoJS

### ISSUE THREAD

**Issue by keiem** [OpenBuilds/OpenBuilds-CONTROL#364]
Hello,

I try to use CONTROL on a arch linux based intel tablet with a X5-Z8350 processor, but it's unworkable slow.  So I was thinking to port Control to NeutralinoJS as they claim it's less resource hungry then electron.
Would this be possible?  I'don't have any experience with javascript, but I have no problem learning it.

**Comment by petervanderwalt** [comment]
Switching platform is going to nothing to change that at all, the Unworkable slowness you feel is the PC unable to keep up with the workload - Electron itself has nothing to do with it. Plus Neutralino looks small until you add the dependencies, and the complicated install instructions to add those dependencies and its right out the window. 

Controlling a CNC is hard work. Lots of behind the scenes queue management, feedback, parsing, event queues, UI updates etc. happening in the application itself You just need a decent CPU (and GPU). 

You can disable some features in CONTROL > Troubleshooting > Application diagnostics (3D viewer needs a lot of CPU/GPU time) to help with slower machines, but at some point its just best to get a proper machine to avoid frustrations.
