### ISSUE TITLE
Cannot connect uCNC - caused by short timeout

### ISSUE THREAD

**Issue by davidedmundson** [OpenBuilds/OpenBuilds-CONTROL#372]
## Issue Title
uCNC (https://github.com/Paciente8159/uCNC) controllers cannot connect flashed on an Arduino mega 
Same for firmware grbl-mega

Running master (c3233c29aca89e89b48b92067dff5f67f33a1bdd)

### Bug Report

Encountered on Linux 

**Steps to Reproduce**

 - Have applicable old hardware
 -  Try to connect
 
 This patch fixes it:
  
index.js
```
-config.grblWaitTime = 0.5;
+config.grblWaitTime = 4;
```

With that we connect flawlessly every time on the first attempt.
Without it, all 4 attempts (even with the DTR version with the  increased timeout length)  would fail every time.
It never reached the 'parser.on("data", function(data) {' callback.

Obviously it's a lazy fix, but definitely an issue. At a minimum we could really increase the timeout for just one of the connection attempts?
Let me know if I can help in any further way, I can run patches.

**Comment by petervanderwalt** [comment]
Consider getting a supported controller like https://us.openbuilds.com/BlackBox-Motion-Control-System-X32

> uCNC (https://github.com/Paciente8159/uCNC) controllers cannot connect

Well technically we only (will and want to) support official gnea/grbl (old but still relevant) and grblHAL

Perhaps request uCNC to be "more grbl compatible" but at this point in time we'd rather not add support for other firmwares, particular rare ones like this. grblHAL is so great, give it a try
