### ISSUE TITLE
F360 Integration

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#44]
Similar to https://github.com/tapnair/UGS_Fusion

**Comment by sharmstr** [comment]
Awesome idea.  Not that you're asking me, but I'd rather have to post do it then a plugin :)

**Comment by openbuilds-engineer** [comment]
Coming soon! (What you see may still change...)

![new tool](https://user-images.githubusercontent.com/31449271/58558979-649cb000-8222-11e9-84db-2651db883ed4.png)

![simpler](https://user-images.githubusercontent.com/31449271/58558976-649cb000-8222-11e9-8be6-070c124c8085.PNG)

![done](https://user-images.githubusercontent.com/31449271/58558975-64041980-8222-11e9-8cc5-2e76df08c801.PNG)

**Comment by petervanderwalt** [comment]
Abandoning plugin https://docs.openbuilds.com/doku.php?id=docs:software:fusion360
