### ISSUE TITLE
MACROs still has a lot of growth ahead (multiline macros, scripting, variables etc) -

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#51]
MACROs still has a lot of growth ahead (multiline macros, scripting, variables etc) -
@swarfer from https://openbuilds.com/threads/openbuilds-control-software.13121/page-7#post-76203

**Comment by jbhurst** [comment]
I've been looking for a way to re-order macros and can't find it.  Can it be done via a text file somewhere?  Once you have a few already set up, if you want to add a new one (say related to the first 3 and needing to group with them), I can't figure out how to do that without deleting them all and starting over.  The ability to use our own icons (.ico, .bmp, whatever) would be nice too, even if not exposed in the UI. 

PS - thanks for all the recent changes.  I'm moving back to Control from bCNC for normal operations and only using it for macros/operations that need a camera.

**Comment by sharmstr** [comment]
https://openbuilds.com/threads/openbuilds-control-software.13121/page-29#post-86666

**Comment by MikonosII** [comment]
How about hot key support for macros?

**Comment by petervanderwalt** [comment]
> How about hot key support for macros?

Checkout v1.0.223 when it comes out in a day or two 


![macro1](https://user-images.githubusercontent.com/31449271/79260496-a829f800-7e8e-11ea-9d37-dea1b65a3d7c.PNG)


![macro2](https://user-images.githubusercontent.com/31449271/79260493-a5c79e00-7e8e-11ea-8ed8-f0aa8f5abb4b.PNG)

**Comment by petervanderwalt** [comment]
> MACROs still has a lot of growth ahead (multiline macros, scripting, variables etc) -
> @swarfer from https://openbuilds.com/threads/openbuilds-control-software.13121/page-7#post-76203

Full Javascript execution (: coming to you in 1.0.229 or later  - access to all the variables, all the functions, and all the magic of JS (setTimeouts, calculations, etc)  

![jsbtns](https://user-images.githubusercontent.com/31449271/79606277-a449e000-80f1-11ea-984f-ea6298f0e1bf.PNG)

![jseditor](https://user-images.githubusercontent.com/31449271/79606265-9eec9580-80f1-11ea-99c1-934e7a5fdeda.PNG)
