### ISSUE TITLE
Z probe - warp compensation

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#62]
Z probe - warp compensation

**Comment by jbhurst** [comment]
We would very much like this as well as table geometry comp.

**Comment by openbuilds-engineer** [comment]
(: its on the far off todo, but expect it to be a few more months

**Comment by excalibur46** [comment]
Hello
Any news about autolever?

**Comment by Thesourceminer** [comment]
Would love to see this as well... Trying to get a handle on the API but the documentation is not quite enough. Some good examples but I feel we need more.
