### ISSUE TITLE
Linux menu icon is huge

### ISSUE THREAD

**Issue by swarfer** [OpenBuilds/OpenBuilds-CONTROL#76]
Under XFCE the menu icon fills the screen instead of being 32x32 like all the other icons.
I tracked down the icon and resized it, rebooted, and that fixed the menu icon size.

**Comment by openbuilds-engineer** [comment]
Probably also upstream fight with Electron or Electron-builder guys. Will look into it

**Comment by openbuilds-engineer** [comment]
https://github.com/OpenBuilds/OpenBuilds-CONTROL/issues/77 is related, did some testing. Closing this one, will continue in #77
