### ISSUE TITLE
Additional key binding options

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#78]
https://openbuilds.com/threads/openbuilds-control-software.13121/page-18#post-82219

Individual Zero for X, Y and Z
Switch for Continuous/incremental jogging.
+- is perfect, in continious it can change feed, in incremental change stepsize

**Comment by openbuilds-engineer** [comment]
Thanks for adding it (: 
Adding to note for myself too... but good chance to investigate how to add Macros here too...

**Comment by WMFB** [comment]
Thanks for logging the request.

**Comment by petervanderwalt** [comment]
```
Switch for Continuous/incremental jogging.
```

![done](https://user-images.githubusercontent.com/31449271/79228757-481d5c80-7e62-11ea-9e3c-62c698a9ca2a.PNG)
Added, refer https://github.com/OpenBuilds/OpenBuilds-CONTROL/issues/121 

```
Bonus: if you are in continuous mode, and hit +/- it jumps back to Incremental too (just felt natural in the workflow - as you are used to +/- affecting Incremental functionality, once you go for those, its good that it goes to incremental mode then (:
```

Still keeping issue open for individual XYZ buttons someday (:

**Comment by petervanderwalt** [comment]
> Adding to note for myself too... but good chance to investigate how to add Macros here too...

Did that ...  v1.0.223

![macro2](https://user-images.githubusercontent.com/31449271/79257075-621e6580-7e89-11ea-91d3-936cdc40d80b.PNG)
![macro1](https://user-images.githubusercontent.com/31449271/79257085-6480bf80-7e89-11ea-9a2b-cef12770d02c.PNG)

**Comment by WMFB** [comment]
> > Adding to note for myself too... but good chance to investigate how to add Macros here too...
> 
> Did that ... v1.0.223
> 
> ![macro2](https://user-images.githubusercontent.com/31449271/79257075-621e6580-7e89-11ea-91d3-936cdc40d80b.PNG)
> ![macro1](https://user-images.githubusercontent.com/31449271/79257085-6480bf80-7e89-11ea-9a2b-cef12770d02c.PNG)

:) Happy Clap.... THANK YOU...
