### ISSUE TITLE
Return from error/power failure

### ISSUE THREAD

**Issue by WMFB** [OpenBuilds/OpenBuilds-CONTROL#80]
Hi, would it be possible to have a logging function in the control software that tracks where in the job you are. And if there's a catastrophic failure, there could be a resume from last operation? 

I'm not too familiar with how GCode is broken up, but it looks similar to logic programming. So there could be counters created for loops and code line numbers.
Just putting it out there... probably was out there anyways.. :)

**Comment by openbuilds-engineer** [comment]
- As Grbl has an internal buffer, its quite hard to track. 
- Also from the controller's perspective, Grbl doesnt offer any power failure recovery / indication power dropped
- GCODE is a modal beast so you cannot just "send from line???" or something, you gotta dig in an set the right modals, then resume.  
- What about laptops: USB keeps powering the controller, laptop battery keeps going. None the wiser
- Motor abruptly stopping means machine position was lost already, cant resume without setting up zero properly again. 
 
All together not a viable option here.  

Invest a UPS (:
