### ISSUE TITLE
Surfacing Wizard - Framing Pass

### ISSUE THREAD

**Issue by WMFB** [OpenBuilds/OpenBuilds-CONTROL#83]
..hope this will make sense...
I used the surfacing wizard last week, it works relatively well. I have a 1.6m x .8m bed and the surfacing took foreeeeever.... but that wasn't the issue. once all the dust had settled ... ;) I noticed that the edge where the surfacing bit turns around and runs in the opposite direction it leaves a small triangle.. sure I could rerun the program with a smaller overlap, but that would take another 3odd hours... can you add a step into the wizard to send the spindle around the border of of the bed. Also my spoilboard stretches 90% of the inside of my bed and sits on the outside boundries of my cutting range. I will probably change this in future so that dust and chips won't collect in there...

anyhoo, it's posted here, not sure if its valuable enough. Thanks for all your help. Your software is awesome.

Waz

**Comment by openbuilds-engineer** [comment]
Implemented in v1.0.180 or newer, please test and report if any issues here.
