### ISSUE TITLE
No way to change mm/in views in jog widget

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#85]
Jog widget defaults to inch mode with no way to change to MM.  View changes made in main app aren't reflected in jog widget so no real way to get it to MM  :)

**Comment by openbuilds-engineer** [comment]
Oops!  Will bring over the changes from main to jog... i always forget lol

**Comment by openbuilds-engineer** [comment]
Fixed in https://github.com/OpenBuilds/OpenBuilds-CONTROL/commit/15160a7f6b2e7b95a91af25cc2723880147bef36
