### ISSUE TITLE
Dont ask to upgrade during a job

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuilds-CONTROL#87]
Hey Peter.  Any chance you can add some logic to the upgrade notification to not alert while a job is running?

https://www.facebook.com/groups/OpenBuilds/permalink/588466615009795/

**Comment by openbuilds-engineer** [comment]
Will do! (;  we really want you to stay up to date at all costs lol!

**Comment by openbuilds-engineer** [comment]
Fixed in v 1.0.180 or newer
