### ISSUE TITLE
Backup/Restore buttons for Macros

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#93]

**Comment by petervanderwalt** [comment]
Thought to self: Export/Import individual macros vs backup

**Comment by petervanderwalt** [comment]
@sharmstr you'll like this one:

Export option (per macro) under the Context menu, and a new Import JSON Macro button (does some very basic sanity check for title!=undefined and codetype!=undefined to avoid random JSON import corrupting array) 

![image](https://user-images.githubusercontent.com/31449271/223211828-c171d53e-4f35-453c-8239-95d3234ee043.png)

**Comment by sharmstr** [comment]
Indeed I do!

**Comment by sharmstr** [comment]
I didnt even know how much I needed the export and import of individual macros.  Awesome job.  I love it.

**Comment by petervanderwalt** [comment]
I had a dream... macros store lol
